spring:
  thymeleaf:
    cache: false #关闭缓存，不然没法看到实时页面
    mode: LEGACYHTML5 #用非严格的HTML，HTML5
    encoding: UTF-8
    servlet:
    	content-type:text/html
  profiles:
  	active: dev
  	#数据源配置
  datasource:
  	url: jdbc:mysql://localhost:3306/ygj_blog?useUnicode=true&characterEncoding=utf8
  	username: root
  	password: 123456
  	driver-class-name: com.mysql.jdbc.Driver

	# 使用druid数据源
	type: com.alibaba.druid.pool.DruidDataSource

#配置mybatis  	
mybatis:
  typeAliasesPackage: com.ygj.blog.entity
  mapperLocations:classpath:mapper/*.xml
  
server:
  port:8080 #Tomcat端口号