spring:
  thymeleaf:
    cache: false #关闭缓存，不然没法看到实时页面
    mode: LEGACYHTML5 #用非严格的HTML，HTML5
    encoding: UTF-8
    servlet:
    	content-type:text/html
    	
server:
  port:8080 #Tomcat端口号